site_name: Insomnes Corner
site_url: https://dengin.xyz/
nav:
  - Home:
    - index.md
  - Blog:
    - blog/index.md
  - Projects: my_projects.md
  - Advent of Code:
    - advent_of_code/index.md
    - 2024:
      - advent_of_code/2024/index.md
      - advent_of_code/2024/01_history.md
      - advent_of_code/2024/02_reports.md
      - advent_of_code/2024/03_mull.md
      - advent_of_code/2024/04_ceres.md
      - advent_of_code/2024/05_queue.md
      - advent_of_code/2024/06_guard.md
      - advent_of_code/2024/07_repair.md
      - advent_of_code/2024/08_resonant.md
      - advent_of_code/2024/09_disk.md
      - advent_of_code/2024/10_hoof.md
      - advent_of_code/2024/11_pebbles.md
      - advent_of_code/2024/12_garden.md
      - advent_of_code/2024/13_claw.md
      - advent_of_code/2024/14_restroom.md
      - advent_of_code/2024/15_warehouse.md
      - advent_of_code/2024/17_computer.md
      - advent_of_code/2024/18_ramrun.md
    - 2021:
      - advent_of_code/2021/index.md
      - advent_of_code/2021/01_sonar_sweep.md
      - advent_of_code/2021/02_dive.md
      - advent_of_code/2021/21_dice.md
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      pygments_lang_class: true
  - pymdownx.superfences
plugins:
  - search
  - social
  - blog:
      categories_allowed:
        - git

theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  search: true
  features:
    # All top navigation keys are now tabs
    - navigation.tabs
    - navigation.footer
    # Allow section pages to have indexes
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - content.code.annotate
extra:
  social:
    - name: My GitHub
      icon: fontawesome/brands/github 
      link: https://github.com/insomnes/
    - name: My LinkedIn
      icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mikhail-dengin/
    - name: Send me an email
      icon: fontawesome/solid/envelope
      link: mailto:mikhail@dengin.xyz
copyright: Copyright &copy; 2024 Mikhail Dengin
